### ISSUE TITLE
Build hangs trying to start or connect to MongoDB

### ISSUE THREAD

**Issue by jochenberger** [sourcemuse/GradleMongoPlugin#39]
Sorry if this is a but unspecific, but I'm not entirely sure what's happening.
I use `test.runWithMongoDb = true` in my build and encounter hangs when the connection is initialized:
```
09:14:00.539 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':test'.
09:14:00.606 [INFO] [org.mongodb.driver.cluster] Cluster created with settings {hosts=[127.0.0.1:12600], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
09:14:00.644 [DEBUG] [org.mongodb.driver.cluster] Updating cluster description to  {type=UNKNOWN, servers=[{address=127.0.0.1:12600, type=UNKNOWN, state=CONNECTING}]
09:14:00.649 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:1}
09:14:00.649 [INFO] [org.mongodb.driver.cluster] Exception in monitor thread while connecting to server 127.0.0.1:12600
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 more
09:14:00.657 [INFO] [org.mongodb.driver.cluster] No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=127.0.0.1:12600, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
09:14:00.664 [DEBUG] [org.mongodb.driver.cluster] Updating cluster description to  {type=UNKNOWN, servers=[{address=127.0.0.1:12600, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Verbindungsaufbau abgelehnt}}]
09:14:01.164 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:2}
09:14:01.664 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:3}
09:14:02.164 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:4}
09:14:02.665 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:5}
09:14:03.165 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:6}
09:14:03.665 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:7}
09:14:04.165 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:8}
09:14:04.665 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:9}
09:14:05.165 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:10}
...
```
This goes on for 30 seconds and then
```
...
09:16:56.223 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:59}
09:16:56.723 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:60}
09:16:57.223 [DEBUG] [org.mongodb.driver.connection] Closing connection connectionId{localValue:61}
09:16:57.303 [DEBUG] [de.flapdoodle.embed.process.store.ArtifactStoreBuilder] Build ArtifactStore(useCache: true)
09:16:57.365 [QUIET] [system.out] Extracting Mongo binaries...
09:16:58.197 [QUIET] [system.out] Starting Mongod 3.2.6 on port 12600...
09:16:58.204 [DEBUG] [de.flapdoodle.embed.process.runtime.ProcessControl] Detected pid: 7538
09:16:58.206 [DEBUG] [de.flapdoodle.embed.process.runtime.ProcessControl] Detected pid: 7539
09:16:58.478 [INFO] [de.flapdoodle.embed.process.runtime.Executable] start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@643fe03b
09:16:58.478 [QUIET] [system.out] Mongod started.
```

**Comment by roberttaylor426** [comment]
What versions of Mongo and the plugin are you using?

**Comment by jochenberger** [comment]
This doesn't seem to matter much. I observe this behavior in different combinations, for example plugin 0.12.0, MongoDB 3.2.6, or plugin 0.10.0, MongoDB 3.2.1, but also with plugin 0.12.0 and the default MongoDB version that it uses.

**Comment by roberttaylor426** [comment]
Ok I think I've found the issue. It turns out the code I wrote to check whether an existing mongo instance is already running performs really badly when there isn't anything there.

I've pushed version `0.13.0-SNAPSHOT` to the snapshots repo, would you mind giving it a try?

**Comment by jochenberger** [comment]
Yes, that one looks better, thanks.

**Comment by roberttaylor426** [comment]
(Lucky) version 0.13.0 just pushed to central.

**Comment by jochenberger** [comment]
Great news, thanks. While you're at dealing with 13's anyway, any plans for #13 ? ;-)

**Comment by roberttaylor426** [comment]
Sure why not? :-)

I'll try to pick it up in the next 24 hours.
